[tool.poetry]
name = "specification"
version = "0.1.0"
description = ""
authors = ["Nikolay <root@k0d.ru>"]

[tool.poetry.dependencies]
python = "^3.8"
mkdocs-material = "^5.5.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
