name: ci
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: git submodule update --init --recursive
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry install --no-dev --no-root
      - run: mkdocs gh-deploy --force
